# -*- coding: utf-8 -*-
"""researchmind.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xx2wF79V08TDI0goesrgp7EMKltoQS67
"""

!pip install -q arxiv pandas sentence-transformers faiss-cpu

import arxiv
import pandas as pd
import numpy as np
import faiss
import torch

from sentence_transformers import SentenceTransformer

import torch

print("Torch:", torch.__version__)

model = SentenceTransformer("all-MiniLM-L6-v2")

print("Sentence Transformer loaded!")

print(arxiv)

TOPIC = input("Enter Research Topic: ")

print("Topic:", TOPIC)

search = arxiv.Search(
    query=TOPIC,
    max_results=20,
    sort_by=arxiv.SortCriterion.Relevance
)

client = arxiv.Client()

print("Search object created successfully!")

papers = []

for result in client.results(search):

    paper = {
        "Title": result.title,
        "Authors": ", ".join(
            [author.name for author in result.authors]
        ),
        "Published": result.published.date(),
        "Abstract": result.summary,
        "PDF_URL": result.pdf_url
    }

    papers.append(paper)

print("Total Papers Retrieved:", len(papers))

print(papers[0]["Title"])

df=pd.DataFrame(papers)
df.head()

print("Rows:",df.shape[0])
print("Columns:",df.shape[1])

for i, title in enumerate(df["Title"]):

    print(f"{i+1}. {title}")

print("TITLE:")
print(df.iloc[0]["Title"])

print("\nAUTHORS:")
print(df.iloc[0]["Authors"])

print("\nABSTRACT:")
print(df.iloc[0]["Abstract"])

df.to_csv(
    "retrieved_papers.csv",
    index=False
)

print("Saved successfully!")

from google.colab import files

files.download("retrieved_papers.csv")

print("Total Papers:", len(df))

print()

print("Oldest Paper:")
print(df["Published"].min())

print()

print("Newest Paper:")
print(df["Published"].max())

for i in range(3):

    print(df.iloc[i]["Title"])

    print(df.iloc[i]["PDF_URL"])

    print("-" * 50)

embedding_model = SentenceTransformer(
    "all-MiniLM-L6-v2"
)

print("Embedding model loaded!")

abstracts = df["Abstract"].tolist()

embeddings = embedding_model.encode(
    abstracts,
    show_progress_bar=True
)

print("Embedding Shape:", embeddings.shape)

dimension = embeddings.shape[1]

index = faiss.IndexFlatL2(dimension)

index.add(
    np.array(embeddings).astype("float32")
)

print("Indexed Papers:", index.ntotal)

faiss.write_index(
    index,
    "research_papers.index"
)

print("FAISS index saved!")

query = input("Ask a research question: ")

print("Question:", query)

query_embedding = embedding_model.encode(
    [query]
)

print(query_embedding.shape)

k = 5

distances, indices = index.search(
    np.array(query_embedding).astype("float32"),
    k
)

print(indices)

for idx in indices[0]:

    print("=" * 80)

    print("TITLE:")
    print(df.iloc[idx]["Title"])

    print()

    print("ABSTRACT:")
    print(df.iloc[idx]["Abstract"][:700])

    print("\n")

retrieved_papers = df.iloc[indices[0]]

retrieved_papers

context = ""

for idx in indices[0]:

    context += df.iloc[idx]["Title"] + "\n"

    context += df.iloc[idx]["Abstract"] + "\n\n"

print(context[:3000])

context = ""

for idx in indices[0]:

    context += f"Title: {df.iloc[idx]['Title']}\n"

    context += f"Abstract: {df.iloc[idx]['Abstract']}\n\n"

print(context[:2000])

!pip install -q transformers

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

model_name = "google/flan-t5-base"

tokenizer = AutoTokenizer.from_pretrained(model_name)

model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

print("LLM Loaded!")

prompt = f"""
Based on the research paper abstracts below, write a concise literature review.

{context}

Literature Review:
"""

context = ""

for idx in indices[0]:

    context += "Title: " + df.iloc[idx]["Title"] + "\n"

    context += df.iloc[idx]["Abstract"][:300] + "\n\n"

inputs = tokenizer(
    prompt,
    return_tensors="pt",
    truncation=True,
    max_length=512
)

outputs = model.generate(
    **inputs,
    max_new_tokens=200,
    do_sample=False
)

review = tokenizer.decode(
    outputs[0],
    skip_special_tokens=True
)

print(review)

print("Sources Used:\n")

for idx in indices[0]:

    print("-" * 80)

    print(df.iloc[idx]["Title"])

    print(df.iloc[idx]["PDF_URL"])

results = {
    "Question": query,
    "Generated_Answer": review
}

print(results)

prompt = f"""
Write a literature review based on these research papers.

Discuss:

1. Main research themes
2. Common methods
3. Current challenges
4. Future directions

Research Papers:

{context}

Literature Review:
"""

inputs = tokenizer(
    prompt,
    return_tensors="pt",
    truncation=True,
    max_length=512
)

outputs = model.generate(
    **inputs,
    max_new_tokens=300,
    do_sample=False
)

literature_review = tokenizer.decode(
    outputs[0],
    skip_special_tokens=True
)

print(literature_review)

prompt = f"""
Based on these research papers:

{context}

Identify:

1. Common research directions
2. Limitations of existing work
3. Potential research gaps
4. Future research opportunities

Research Gap Analysis:
"""

inputs = tokenizer(
    prompt,
    return_tensors="pt",
    truncation=True,
    max_length=512
)

outputs = model.generate(
    **inputs,
    max_new_tokens=300,
    do_sample=False
)

research_gap = tokenizer.decode(
    outputs[0],
    skip_special_tokens=True
)

print(research_gap)

all_text = ""

for i in range(len(df)):

    all_text += df.iloc[i]["Title"] + " "

    all_text += df.iloc[i]["Abstract"] + " "

print("Text collected!")

!pip install -q nltk

import nltk

from nltk.corpus import stopwords

from collections import Counter

nltk.download("stopwords")

stop_words = set(stopwords.words("english"))

words = all_text.lower().split()

clean_words = []

for word in words:

    word = word.strip(".,()[]{}:;!?\"'")

    if len(word) > 3 and word not in stop_words:

        clean_words.append(word)

print("Words cleaned!")

word_counts = Counter(clean_words)

top_words = word_counts.most_common(20)

top_words

print("Top Research Trends\n")

for word, count in top_words:

    print(f"{word}: {count}")

research_phrases = [

    "large language model",

    "retrieval augmented generation",

    "rag",

    "llm ensemble",

    "agent",

    "multi agent",

    "reasoning",

    "fine tuning",

    "knowledge graph",

    "hallucination",

    "benchmark",

    "inference",

    "alignment",

    "tool learning",

    "prompt engineering",

    "recommendation system",

    "graph neural network"
]

phrase_counts = {}

text = all_text.lower()

for phrase in research_phrases:

    phrase_counts[phrase] = text.count(
        phrase.lower()
    )

sorted_trends = sorted(
    phrase_counts.items(),
    key=lambda x: x[1],
    reverse=True
)

print("Research Trend Analysis\n")

for phrase, count in sorted_trends:

    if count > 0:

        print(
            f"{phrase}: {count}"
        )

report = ""

report += "=" * 60 + "\n"
report += "RESEARCH PAPER ASSISTANT REPORT\n"
report += "=" * 60 + "\n\n"

report += f"Research Topic: {TOPIC}\n\n"

report += f"Number of Papers Retrieved: {len(df)}\n\n"

report += "TOP RESEARCH TRENDS\n"
report += "-" * 30 + "\n"

for phrase, count in sorted_trends:

    if count > 0:

        report += f"{phrase}: {count}\n"

report += "\n"

report += "TOP RELEVANT PAPERS\n"
report += "-" * 30 + "\n"

for idx in indices[0]:

    report += (
        df.iloc[idx]["Title"] + "\n"
    )

report += "\n"

report += "LITERATURE REVIEW\n"
report += "-" * 30 + "\n"

report += literature_review

report += "\n\n"

report += "QUESTION ANSWERING\n"
report += "-" * 30 + "\n"

report += f"Question: {query}\n\n"

report += f"Answer: {review}\n\n"

print(report[:5000])

with open(
    "research_report.txt",
    "w",
    encoding="utf-8"
) as f:

    f.write(report)

print(
    "Report saved successfully!"
)

from google.colab import files

files.download(
    "research_report.txt"
)

